INSERT INTO universities(name,logo_url,background_url) VAlUES ('University of Houston','https://d7vte2v9l4dqd.cloudfront.net/universityOfHoustonLogo.png','https://d7vte2v9l4dqd.cloudfront.net/University of Houston.jpg');
INSERT INTO universities(name,logo_url,background_url) VAlUES ('University of Arizona','https://d7vte2v9l4dqd.cloudfront.net/universityOfArizona.png','https://d7vte2v9l4dqd.cloudfront.net/University of Arizona.jpeg');
INSERT INTO universities(name,logo_url,background_url) VAlUES ('Oregon State University','https://d7vte2v9l4dqd.cloudfront.net/universityOfOregon.png','https://d7vte2v9l4dqd.cloudfront.net/Oregon');
INSERT INTO universities(name,logo_url,background_url) VAlUES ('Pepperdine University','https://d7vte2v9l4dqd.cloudfront.net/pepperdineUniversityLogo.png','https://d7vte2v9l4dqd.cloudfront.net/Pepperdine');

-- INSERT INTO users(name,password,email,role,university_id) VALUES ('Jonathon Wazney','password@1','5jwazney@gmail.com',1,1);
INSERT INTO users (name,password,email,role,university_id)
VALUES
  ('Yoshio Hurley','FMM16N','et.arcu@techport.com','admin',3),
  ('Hector Mitchell','UAW66V','purus.in.molestie@techport.com','admin',3),
  ('Carl Parks','RNH87P','non.hendrerit@techport.com','admin',1),
  ('Hayley Fulton','NUI41C','non.leo.vivamus@techport.com','admin',4),
  ('Daniel Lane','PPT61Q','semper@techport.com','admin',2),
  ('Linda Dudley','XUO12Q','mauris.eu@techport.com','admin',2),
  ('Ian Camacho','GTV54K','ullamcorper@techport.com','admin',1),
  ('Damian Cash','YJT15Y','euismod.est.arcu@techport.com','admin',4);
  ('Jeremy Smith', 'HDO56DF','jeremy.smith@techport.com', 'admin',null)

INSERT INTO users (name,password,email,role,university_id)
VALUES
  ('Wade Marshall','ADH58Z','id@techport.com','tech',1),
  ('Dante Abbott','RNT74L','arcu.vestibulum.ante@techport.com','tech',1),
  ('Jesse Espinoza','JLM66O','ornare.lectus@techport.com','tech',1),
  ('Chaney Castillo','VYI53K','lectus.pede@techport.com','tech',1),
  ('Yardley Padilla','GOX75Z','blandit.mattis@techport.com','tech',1),
  ('Wallace Joseph','PCG21M','aliquet.magna.a@techport.com','tech',1),
  ('Cedric Hendrix','PMW63B','mauris@techport.com','tech',1),
  ('Pearl Abbott','QQH57N','purus.gravida.sagittis@techport.com','tech',1),
  ('Sheila Johns','RMZ77X','pharetra@techport.com','tech',1),
  ('Daria Edwards','IEO08R','proin@techport.com','tech',1),
  ('Violet Dillon','ZLR41D','eu.euismod.ac@techport.com','tech',1),
  ('Samuel Meyers','YNS04P','erat.vel.pede@techport.com','tech',1),
  ('Cynthia Delaney','MXF25P','purus.ac@techport.com','tech',1),
  ('Ciara Trujillo','BBD81V','ante.dictum@techport.com','tech',1),
  ('Serena Benson','QKQ84T','non.massa@techport.com','tech',1),
  ('Brady Dean','QHR93U','consequat.enim@techport.com','tech',1),
  ('Edan Coleman','IYH92L','suspendisse.commodo@techport.com','tech',1),
  ('Sigourney Barton','LBU15J','vitae.sodales@techport.com','tech',1),
  ('Imelda Conley','XWP36F','morbi@techport.com','tech',1),
  ('Tate Paul','RBZ71L','lectus@techport.com','tech',1),
  ('Aladdin Howard','QPK86W','donec@techport.com','tech',1),
  ('Grady Ruiz','WWV54J','cursus.a.enim@techport.com','tech',1),
  ('Rhona Waller','KCT33P','phasellus.dolor@techport.com','tech',1),
  ('Forrest Skinner','RJD51R','mattis.velit.justo@techport.com','tech',1),
  ('Jared Estes','WKZ28S','velit.eu@techport.com','tech',1);  

INSERT INTO users (name,password,email,role,university_id)
VALUES
  ('Matthew Brewer','PRQ80G','id@techport.com','tech',2),
  ('Donna Mcconnell','GFH80Y','mauris@techport.com','tech',2),
  ('Ifeoma Gill','MWA63N','a@techport.com','tech',2),
  ('Germane Hays','GJX94N','imperdiet.nec@techport.com','tech',2),
  ('Lillian Hicks','UTI40S','duis.sit.amet@techport.com','tech',2),
  ('Andrew Cantrell','CDH77F','vel@techport.com','tech',2),
  ('Tyler Pierce','SYP13B','fames.ac.turpis@techport.com','tech',2),
  ('Susan Oliver','FFN49U','magna.a@techport.com','tech',2),
  ('Tasha Guy','LOB56K','ac.fermentum.vel@techport.com','tech',2),
  ('Hedwig Norman','HHE00S','donec.fringilla.donec@techport.com','tech',2),
  ('Teegan Barker','MJH48E','non.luctus@techport.com','tech',2),
  ('Yeo Sharpe','DXW31T','ipsum.porta@techport.com','tech',2),
  ('Patricia Baxter','JZM22M','facilisi@techport.com','tech',2),
  ('Alexander Jacobson','CFY35N','id.erat.etiam@techport.com','tech',2),
  ('Lyle Stone','BCX90Q','ac.mi@techport.com','tech',2),
  ('Britanni Douglas','WUE06M','commodo.ipsum@techport.com','tech',2),
  ('Illiana Hill','JTC69O','et.ultrices.posuere@techport.com','tech',2),
  ('Meredith Gutierrez','MDB55Q','elit@techport.com','tech',2),
  ('Laura Sherman','KXD77P','ullamcorper.magna@techport.com','tech',2),
  ('Dane Glass','CCO11C','ultricies.adipiscing@techport.com','tech',2),
  ('Buffy Tanner','DAV88L','nibh.enim@techport.com','tech',2),
  ('Chancellor Terry','ENY31T','tellus@techport.com','tech',2),
  ('Jayme Wall','BVQ36G','dictum@techport.com','tech',2),
  ('Colby Keith','RXD53P','orci.consectetuer.euismod@techport.com','tech',2),
  ('Rhiannon Hammond','DWH52T','donec.feugiat@techport.com','tech',2);

INSERT INTO users (name,password,email,role,university_id)
VALUES
  ('Clinton Terrell','MGY36Q','nunc.lectus.pede@techport.com','tech',3),
  ('Dalton Russell','NGM39T','ullamcorper@techport.com','tech',3),
  ('Debra Mathews','MJY26D','vel.convallis.in@techport.com','tech',3),
  ('Imani Anderson','FSP85T','elementum.at@techport.com','tech',3),
  ('Donovan Clemons','LHW45G','ullamcorper.velit@techport.com','tech',3),
  ('Elvis Benson','MJK57M','odio.nam@techport.com','tech',3),
  ('Mohammad Rivas','PHJ74G','a.nunc@techport.com','tech',3),
  ('Deirdre Burt','URT19I','massa.lobortis@techport.com','tech',3),
  ('Regina Christensen','SXZ77X','ipsum.ac@techport.com','tech',3),
  ('Quyn Blackburn','KVY36K','tempor@techport.com','tech',3),
  ('Petra Walls','UHG35C','nunc.ullamcorper@techport.com','tech',3),
  ('Shaeleigh Burt','EGG55V','auctor.velit.eget@techport.com','tech',3),
  ('Shaine Horne','UZN62G','cras@techport.com','tech',3),
  ('Macy Cain','YAC64Q','et@techport.com','tech',3),
  ('Orlando Shaw','DLA91L','diam.luctus@techport.com','tech',3),
  ('Anjolie Nieves','NJD95P','quis.arcu@techport.com','tech',3),
  ('Denton Randall','LFT53L','sagittis.augue.eu@techport.com','tech',3),
  ('Reuben Carpenter','EKJ76I','id.blandit@techport.com','tech',3),
  ('Carter Fox','QCP36I','ullamcorper.eu.euismod@techport.com','tech',3),
  ('Elizabeth Mckinney','QVE67G','nunc.mauris@techport.com','tech',3),
  ('Mercedes Hogan','HUI11T','mauris.eu@techport.com','tech',3),
  ('Blythe Austin','JMV84P','nonummy.fusce@techport.com','tech',3),
  ('Venus Schneider','CRY33E','ligula@techport.com','tech',3),
  ('Alden Puckett','NUQ95O','fusce@techport.com','tech',3),
  ('Galena Watkins','FTL50G','eu@techport.com','tech',3);

INSERT INTO users (name,password,email,role,university_id)
VALUES
  ('Medge Diaz','VLK73M','sed.leo@techport.com','tech',4),
  ('Zenia Sears','WCD28T','ultrices.mauris.ipsum@techport.com','tech',4),
  ('Todd Patel','TPF64P','integer@techport.com','tech',4),
  ('Orlando Hobbs','PSC64W','nulla.aliquet.proin@techport.com','tech',4),
  ('Guy Flynn','KYY03I','urna.justo@techport.com','tech',4),
  ('Kaitlin Cotton','MLI13X','nec.mollis.vitae@techport.com','tech',4),
  ('Carly Vinson','ZMF93S','egestas@techport.com','tech',4),
  ('Aileen Armstrong','XAH19N','consectetuer.adipiscing@techport.com','tech',4),
  ('Lee Richardson','WSD20R','vitae.diam@techport.com','tech',4),
  ('Freya Stewart','UMO26I','urna.nullam.lobortis@techport.com','tech',4),
  ('Scarlet Aguilar','HDG66J','neque@techport.com','tech',4),
  ('Hayden Rice','XHG58P','ornare.lectus.justo@techport.com','tech',4),
  ('Ezekiel Chan','HSG46W','convallis.est@techport.com','tech',4),
  ('Lacota Massey','BSE19I','eros.nec.tellus@techport.com','tech',4),
  ('Xanthus Carter','OYJ53G','vestibulum@techport.com','tech',4),
  ('Macaulay James','IHX26B','nulla.vulputate@techport.com','tech',4),
  ('Allistair Copeland','JOC71L','maecenas.malesuada@techport.com','tech',4),
  ('Kyla Carlson','SFL98B','hendrerit@techport.com','tech',4),
  ('Fleur Estrada','JWT01E','lacus.aliquam@techport.com','tech',4),
  ('Macaulay Michael','IIK53I','at.egestas.a@techport.com','tech',4),
  ('Aspen Hutchinson','AJQ25P','et.magnis@techport.com','tech',4),
  ('Rafael Walter','QJA12P','ac.feugiat@techport.com','tech',4),
  ('Marvin Gillespie','OOB04T','nulla@techport.com','tech',4),
  ('Madison Chambers','HSY22X','luctus@techport.com','tech',4),
  ('Charity West','GXC28G','dapibus.gravida@techport.com','tech',4);    

-- INSERT INTO tickets(problem,description,note,point_of_contact,location,priority,status,university_id,assigned_tech) VALUES ('projector','Fix projector light','need to order new light','miss.jackson ex#','room 213',2,1,1,1);

INSERT INTO tickets (problem,description,note,point_of_contact,location,priority,status,university_id,assigned_tech)
VALUES
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','Urgent','assigned',1,26),
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','Urgent','assigned',1,24),
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','Urgent','assigned',1,30),
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','Routine','working',1,21),
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','Routine','working',1,15),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','Routine','working',1,30),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','severe','working',1,9),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','severe','complete',1,14),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','severe','complete',1,19),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','Urgent','assigned',1,15),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','Urgent','assigned',1,10),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','Urgent','assigned',1,29),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','Routine','working',1,26),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','Routine','working',1,23),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','Routine','working',1,10),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','severe','complete',1,24),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','severe','complete',1,27),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','severe','complete',1,33),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','Urgent','assigned',1,31),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','Urgent','assigned',1,15),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','Urgent','assigned',1,17),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','Routine','working',1,14),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','Routine','working',1,19),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','Routine','working',1,31),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','severe','complete',1,15),
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','severe','complete',1,11),
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','severe','complete',1,18),
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','Urgent','assigned',1,12),
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','Urgent','assigned',1,16),
  ('projector','fix problem','working','Mrs.Tolli Ext:748','room 213','Urgent','assigned',1,18),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','Routine','working',1,21),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','Routine','working',1,27),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','Routine','working',1,12),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','severe','complete',1,33),
  ('toilet','fix problem','ordering part','Miss.Wong Ext:783','room 356','severe','complete',1,12),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','severe','complete',1,11),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','Urgent','assigned',1,19),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','Urgent','assigned',1,19),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','Urgent','assigned',1,13),
  ('whiteboard','fix problem','need more information','Mr.Ross Ext:369','room 246','Routine','working',1,20),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','Routine','working',1,25),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','Routine','working',1,16),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','severe','complete',1,12),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','severe','complete',1,20),
  ('computer','fix problem','needs third party work','Miss.Jackson Ext:351','room 381','severe','complete',1,15),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','Urgent','assigned',1,12),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','Urgent','assigned',1,11),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','Urgent','assigned',1,30),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','Routine','working',1,29),
  ('shredder','fix problem','wrapping up paperwork','Mr.Edwards Ext:983','room 415','Routine','working',1,15);

INSERT INTO tickets (problem,description,note,point_of_contact,location,priority,status,university_id,assigned_tech)
VALUES
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','Urgent','assigned',2,39),
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','Urgent','assigned',2,51),
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','Urgent','assigned',2,55),
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','Routine','working',2,41),
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','Routine','working',2,53),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','Routine','working',2,41),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','severe','complete',2,55),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','severe','complete',2,37),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','severe','complete',2,42),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','Urgent','assigned',2,36),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','Urgent','assigned',2,55),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','Urgent','assigned',2,55),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','Routine','working',2,42),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','Routine','working',2,50),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','Routine','working',2,44),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','severe','complete',2,39),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','severe','working',2,49),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','severe','working',2,53),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','Urgent','assigned',2,49),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','Urgent','assigned',2,42),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','Urgent','assigned',2,40),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','Routine','working',2,51),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','Routine','working',2,37),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','Routine','working',2,41),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','severe','complete',2,44),
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','severe','complete',2,51),
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','severe','complete',2,42),
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','Urgent','assigned',2,54),
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','Urgent','assigned',2,36),
  ('projector','fix problem','working','Mr.Diamacus Ext:356','room 364','Urgent','assigned',2,35),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','Routine','working',2,54),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','Routine','working',2,52),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','Routine','working',2,53),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','severe','complete',2,41),
  ('toilet','fix problem','ordering part','Miss.Smith Ext: 587','room 412','severe','complete',2,39),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','severe','working',2,39),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','Urgent','assigned',2,43),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','Urgent','assigned',2,35),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','Urgent','assigned',2,45),
  ('whiteboard','fix problem','need more information','Mrs.Ramero Ext:657','room 568','Routine','working',2,37),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','Routine','working',2,40),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','Routine','working',2,35),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','severe','complete',2,46),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','severe','complete',2,46),
  ('computer','fix problem','needs third party work','Mr.Cunningham Ext:649','room 398','severe','complete',2,35),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','Urgent','assigned',2,42),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','Urgent','assigned',2,54),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','Urgent','assigned',2,44),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','Routine','working',2,53),
  ('shredder','fix problem','wrapping up paperwork','Miss.Tori Ext:813','room 467','Routine','working',2,44);

INSERT INTO tickets (problem,description,note,point_of_contact,location,priority,status,university_id,assigned_tech)
VALUES
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','Urgent','assigned',3,69),
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','Urgent','assigned',3,80),
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','Urgent','assigned',3,71),
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','Routine','working',3,68),
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','Routine','complete',3,75),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','Routine','working',3,69),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','severe','complete',3,66),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','severe','complete',3,59),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','severe','complete',3,72),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','Urgent','assigned',3,79),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','Urgent','assigned',3,66),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','Urgent','assigned',3,69),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','Routine','working',3,81),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','Routine','complete',3,82),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','Routine','working',3,70),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','severe','complete',3,74),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','severe','complete',3,72),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','severe','complete',3,74),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','Urgent','assigned',3,64),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','Urgent','assigned',3,78),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','Urgent','assigned',3,65),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','Routine','working',3,77),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','Routine','working',3,69),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','Routine','working',3,67),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','severe','complete',3,73),
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','severe','complete',3,82),
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','severe','complete',3,59),
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','Urgent','assigned',3,69),
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','Urgent','assigned',3,59),
  ('projector','fix problem','working','Mr.Wellington Ext:921','room 419','Urgent','assigned',3,73),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','Routine','working',3,78),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','Routine','working',3,61),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','Routine','working',3,59),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','severe','complete',3,65),
  ('toilet','fix problem','ordering part','Mr.Downing Ext:648','room 357','severe','complete',3,79),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','severe','complete',3,66),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','Urgent','assigned',3,82),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','Urgent','assigned',3,72),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','Urgent','assigned',3,58),
  ('whiteboard','fix problem','need more information','Miss.Plainfield Ext:654','room 315','Routine','working',3,65),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','Routine','working',3,65),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','Routine','working',3,73),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','severe','complete',3,67),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','severe','complete',3,71),
  ('computer','fix problem','needs third party work','Mrs.Golindo Ext:315','room 584','severe','complete',3,72),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','Urgent','assigned',3,79),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','Urgent','assigned',3,62),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','Urgent','assigned',3,73),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','Routine','working',3,64),
  ('shredder','fix problem','wrapping up paperwork','Miss.Gonzalez Ext:248','room 549','Routine','working',3,61);

INSERT INTO tickets (problem,description,note,point_of_contact,location,priority,status,university_id,assigned_tech)
VALUES
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','Urgent','assigned',4,89),
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','Urgent','assigned',4,89),
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','Urgent','assigned',4,92),
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','Routine','working',4,99),
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','Routine','working',4,97),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','Routine','working',4,100),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','severe','complete',4,86),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','severe','complete',4,97),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','severe','complete',4,101),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','Urgent','assigned',4,104),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','Urgent','assigned',4,84),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','Urgent','assigned',4,91),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','Routine','working',4,100),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','Routine','working',4,100),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','Routine','working',4,89),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','severe','complete',4,107),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','severe','complete',4,103),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','severe','complete',4,101),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','Urgent','assigned',4,101),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','Urgent','assigned',4,92),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','Urgent','assigned',4,85),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','Routine','working',4,94),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','Routine','working',4,90),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','Routine','working',4,98),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','severe','complete',4,106),
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','severe','complete',4,98),
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','severe','complete',4,95),
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','Urgent','assigned',4,83),
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','Urgent','assigned',4,84),
  ('projector','fix problem','working','Mr.Goldblum Ext:348','room 578','Urgent','assigned',4,94),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','Routine','working',4,100),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','Routine','working',4,86),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','Routine','working',4,106),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','severe','complete',4,89),
  ('toilet','fix problem','ordering part','Mr.Semani Ext: 359','room 437','severe','complete',4,105),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','severe','complete',4,91),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','Urgent','assigned',4,105),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','Urgent','assigned',4,83),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','Urgent','assigned',4,97),
  ('whiteboard','fix problem','need more information','Miss.Ontario Ext: 682','room 386','Routine','working',4,90),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','Routine','working',4,93),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','Routine','working',4,86),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','severe','complete',4,101),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','severe','complete',4,90),
  ('computer','fix problem','needs third party work','Mrs.Albert Ext: 734','room 246','severe','complete',4,83),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','Urgent','assigned',4,100),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','Urgent','assigned',4,102),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','Urgent','assigned',4,85),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','Routine','working',4,86),
  ('shredder','fix problem','wrapping up paperwork','Mr.Clayman Ext: 569','room 168','Routine','working',4,88);
